### PR TITLE
Add listattendence,deleteevent, unmark commands bug fixes in mark

### LINKED ISSUE #120: add command to unmark attendance, list attendance events, delete attendance events

### LINKED ISSUE #121: Fix bugs in mark, unmark and listattendance commands
all 3 commands allow for multiple e/ prefixes and duplicates

### PR DESCRIPTION
**Pull request by ishan-agarwal-05**
fixes #120 
fixes #121 

**Summary of Changes:**

1. Create `UnmarkAttendanceCommand`
2. Create `ListEventsCommand`
3. Create `DeleteEventCommand`

4. **Bug Fixes and Prefix Handling for Attendance Commands:**
   - **Create, Mark, Unmark, List Event Commands:**
     - Added checks to disallow multiple `e/` prefixes in commands that only handle one event at a time.
     - Ensured proper error messages are displayed if multiple event names are provided.
   - **Create and Delete Events Commands:**
     - Allowed multiple `e/` prefixes to create or delete multiple events at once.
     - Added validation to prevent duplicate event names in input and to check for events that already exist or don't exist.

5. Code Cleanup

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CreateAttendanceEventCommand.java [hunk 1]
```diff
@@ -17,21 +19,34 @@ public class CreateAttendanceEventCommand extends Command {
     public static final String MESSAGE_SUCCESS = "Created attendance event: %1$s";
     public static final String MESSAGE_DUPLICATE_EVENT = "This attendance event already exists.";
 
-    private final String eventName;
+    private final List<String> eventNames;
```
Comment (gabriellegtw) [inline src/main/java/seedu/address/logic/commands/CreateAttendanceEventCommand.java:22]: Nice to see that you have used the proper naming conventions for collections!

File: src/main/java/seedu/address/logic/commands/CreateAttendanceEventCommand.java [hunk 2]
```diff
@@ -17,21 +19,34 @@ public class CreateAttendanceEventCommand extends Command {
...
+     *
+     * @param model {@code Model} which the command should operate on.
+     * @return {@code CommandResult} that describes the success of the command.
+     * @throws CommandException If an error occurs during command execution.
+     */
     @Override
     public CommandResult execute(Model model) throws CommandException {
-        if (model.getAttendanceEvent(eventName).isPresent()) {
-            throw new CommandException(MESSAGE_DUPLICATE_EVENT);
+        for (String eventName : eventNames) {
```
Comment (gabriellegtw) [inline src/main/java/seedu/address/logic/commands/CreateAttendanceEventCommand.java:37]: I think test cases should be added for this class to increase code coverage

File: src/main/java/seedu/address/logic/commands/ListEventsCommand.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+    public static final String COMMAND_WORD = "listevents";
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Lists all attendance events.\n"
+            + "Example: " + COMMAND_WORD;
+
+    public static final String MESSAGE_SUCCESS = "Attendance Events:\n%1$s";
+    public static final String MESSAGE_NO_EVENTS = "There are no attendance events to display.";
+
+    @Override
+    public CommandResult execute(Model model) throws CommandException {
```
Comment (gabriellegtw) [inline src/main/java/seedu/address/logic/commands/ListEventsCommand.java:25]: Could there be more additions of definsive coding here? eg. try/catch, assertions, logger?

File: src/test/java/seedu/address/stubs/delete/ModelManagerStub.java [hunk 4]
```diff
@@ -167,4 +167,9 @@ public ObservableList<AttendanceEvent> getAttendanceEventList() {
     public List<Person> getStudentsByAttendance(String eventName, boolean isPresent) {
         return Collections.emptyList();
     }
+
+    @Override
+    public void deleteAttendanceEvent(AttendanceEvent event) {
```
Comment (gabriellegtw) [inline src/test/java/seedu/address/stubs/delete/ModelManagerStub.java:172]: Hmm should the class still be overridden if you planning to make most of the inherited methods redundant?

File: src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+     * @throws ParseException if the user input does not conform to the expected format.
+     */
+    @Override
+    public UnmarkAttendanceCommand parse(String userInput) throws ParseException {
+        ArgumentMultimap argMultimap =
+                ArgumentTokenizer.tokenize(userInput, PREFIX_EVENT, PREFIX_INDEX);
+
+
+
+        if (!argMultimap.getValue(PREFIX_EVENT).isPresent() || !argMultimap.getValue(PREFIX_INDEX).isPresent()
```
Comment (gabriellegtw) [inline src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java:34]: Hmm can this if else statement be written in a more readable way?

**Review by gabriellegtw — COMMENTED** [review]
LGTM. Perhaps more assertions and loggers could be added

File: src/test/java/seedu/address/stubs/delete/ModelManagerStub.java (hunk 4 above)
Comment (ishan-agarwal-05) [reply src/test/java/seedu/address/stubs/delete/ModelManagerStub.java:172]: you have to override the methods on abstract model in the stub to avoid compilation errors.

File: src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java (hunk 5 above)
Comment (ishan-agarwal-05) [reply src/main/java/seedu/address/logic/parser/UnmarkAttendanceCommandParser.java:34]: what do you suggest is should have here instead? i used this because i was copying the format in add command
