### PR TITLE
Fix Edit test cases

### LINKED ISSUE #84: Fix test cases for edit command
Some test cases are disabled because it involves tag which @gabriellegtw will work on in v1.4

### PR DESCRIPTION
**Pull request by gabriellegtw**
Fixes #84 

This excludes those test cases with tags involved

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java [hunk 1]
```diff
@@ -11,13 +11,12 @@
...
 import static seedu.address.logic.commands.CommandTestUtil.VALID_TAG_HUSBAND;
 
-import org.junit.jupiter.api.Disabled;
 import org.junit.jupiter.api.Test;
 
 import seedu.address.logic.commands.EditCommand.EditPersonDescriptor;
 import seedu.address.testutil.EditPersonDescriptorBuilder;
 
-@Disabled
+
```
Comment (Wnayar) [inline src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java:19]: Good job adding test cases for the edit command!

**Review by Wnayar — APPROVED** [review]

**Review by Wnayar — APPROVED** [review]
LGTM!
