### PR TITLE
Fixes overflow of integer error message for parsing index

### LINKED ISSUE #91: Fix integer overflow error messages for delete
Fixes integer overflow parsing and error messages for delete

### PR DESCRIPTION
**Pull request by Wnayar**
Fixes #91

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -77,7 +77,18 @@ public static boolean isNotIntegerOverflow(String trimmedIndex) {
...
-            long value = Long.parseLong(trimmedIndex);
+            if (trimmedIndex.startsWith("-")) {
+                return true;
+            }
+            if (trimmedIndex.length() > 10) {
+                return false;
+            }
+            if (trimmedIndex.length() == 10) {
+                // lexicographically checks if index is less than max integer
+                return trimmedIndex.compareTo(String.valueOf(Integer.MAX_VALUE)) <= 0;
```
Comment (gabriellegtw) [inline src/main/java/seedu/address/commons/util/StringUtil.java:88]: good idea of fixing integer overflow!

**Review by gabriellegtw — COMMENTED** [review]
LGTM
