### PR TITLE
Fix alpha bugs for show and offlinehelp

### LINKED ISSUE #150: Bug: show - invalid input still updates UI
Type: feature flaw, feature less useful than it can be 

UI changes to show an empty list despite group number entered being invalid (such as negative numbers)

### LINKED ISSUE #165: Bug: list - space/s before keyword prevent the command from being parsed
Type: Feature flaw, overzealous input validation and specificity of error messages

Input:  list , there are spaces in front

Output: Invalid command format!  list: Lists all users. There should be no parameters! Example: list

### PR DESCRIPTION
**Pull request by gabriellegtw**
Fixes #165 
Fixes #150

### CODE REVIEW

File: src/test/java/seedu/address/testutil/TypicalPersons.java [hunk 1]
```diff
@@ -25,23 +25,24 @@ public class TypicalPersons {
 
     public static final Person ALICE = new PersonBuilder().withName("Alice Pauline")
             .withMajor("Computer Science").withEmail("e1234567@u.nus.edu")
-            .withStudentId("A1234567P").withYear("2").withComment("Shes a very vocal person")
+            .withStudentId("A1234567P").withYear("2").withTags("group 1").withComment("Shes a very vocal person")
```
Comment (NicholasT1) [inline src/test/java/seedu/address/testutil/TypicalPersons.java:28]: Maybe withTags should be renamed to withGroup
