### PR TITLE
Branch comment bug fix

### LINKED ISSUE #124: Comment bug fix
Fix bug in comment and update UML

### PR DESCRIPTION
**Pull request by Wnayar**
Fixes #124

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -89,4 +89,18 @@ public static boolean isNotIntegerOverflow(String trimmedIndex) {
...
     }
+
+    /**
+     * Returns true if {@code s} does not represent a number as it contains other chars whic are not numbers
+     * e.g. e, w, {, ] <br>
+     * Will return false for any other non-null string input
+     * e.g. empty string, "-1", "0", "+1", and " 2 " (untrimmed), "3 0" (contains whitespace), "1 a" (contains letters)
+     * @throws NullPointerException if {@code s} is null.
+     */
+    public static boolean isNotNumber(String trimmedIndex) {
```
Comment (NicholasT1) [inline src/main/java/seedu/address/commons/util/StringUtil.java:100]: Perhaps can name it as a verb so it sounds more like a method

**Review by NicholasT1 — APPROVED** [review]
